### ISSUE TITLE
[Team-3] Feedback from demo 3

### ISSUE THREAD

**Issue by piazzadario** [giovannitangredi/PULSeBS#24]
Hi guys,  as a B.Sc. student, I would appreciate if you can change the color of the button inside the "Bookings" column, so that it matches the color of the event inside the calendar (e.g. green-green if I'm booked, or grey-grey if I'm in the waiting list). As an alternative, you can make it of a different color, but providing a text feedback, because I find this color mismatch a bit confusing. Besides that, good job 👍 
Thank you for your attention,
👨🏼‍🔧 Giovanni: first year BSc student

**Comment by giovannitangredi** [comment]
Thanks for the feedback, we resolved the issue as requested
